### ISSUE TITLE
Check in an example of a runnable mylang program

### ISSUE THREAD

**Issue by philipcraig** [jbcoe/mylang#54]

**Comment by philipcraig** [comment]
Funny thing, that program crashes!

```
D:\Work\mylang>cargo run --quiet -- sample.my
1:1 Let 'let',
1:5 Identifier 'x',
1:7 EqualSign '=',
1:9 String '"Hello"',
1:16 SemiColon ';',
2:1 Let 'let',
2:5 Identifier 'y',
2:7 EqualSign '=',
2:9 Integer '72',
2:11 SemiColon ';',
3:1 Let 'let',
3:5 Identifier 'z',
3:7 EqualSign '=',
3:9 Minus '-',
3:10 FloatingPoint '3.14159',
3:17 SemiColon ';',
4:1 Return 'return',
4:8 Identifier 'y',
4:9 SemiColon ';',
5:1 EndOfFile '',
thread 'main' panicked at 'Unhandled expression kind in top-level let statement UnaryMinus(FloatingPoint(FloatingPointExpression { value: 3.14159 }))', src\frame.rs:51:25
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\std\src\panicking.rs:493
   1: std::panicking::begin_panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\std\src\panicking.rs:435
   2: mylang::frame::Frame::evaluate_statement
             at .\src\frame.rs:51
   3: mylang::frame::Frame::evaluate_body
             at .\src\frame.rs:23
   4: mylang::evaluator::Evaluator::evaluate
             at .\src\evaluator.rs:23
   5: mylang::driver::process_text<mut std::io::stdio::StdoutLock*>
             at .\src\driver.rs:90
   6: mylang::driver::process_stream<std::fs::File,mut std::io::stdio::StdoutLock*>
             at .\src\driver.rs:56
   7: mylang::driver::real_main
             at .\src\driver.rs:41
   8: mylang::main
             at .\src\main.rs:7
   9: core::ops::function::FnOnce::call_once<fn() -> core::result::Result<tuple<>, anyhow::Error>,tuple<>>
             at D:\cargo-home\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by philipcraig** [comment]
Done in #60
